// src/svelte/components/ButtonGroup.svelte
<script lang="ts">
  export type ButtonAction = {
    label: string;
    onClick: () => void;
  };

  let { buttons } = $props<{ buttons: ButtonAction[] }>();
</script>

<div class="design-kit-button-group">
  {#each buttons as button (button.label)}
    <button class="design-kit-button" onclick={button.onClick}>
      {button.label}
    </button>
  {/each}
</div>

// src/solid/components/ButtonGroup.tsx
import { For } from 'solid-js';

interface ButtonGroupProps {
  buttons: Array<{
    label: string;
    onClick: () => void;
  }>;
}

export function ButtonGroup(props: ButtonGroupProps) {
  return (
    <div class="design-kit-button-group">
      <For each={props.buttons}>
        {(button) => (
          <button class="design-kit-button" onClick={button.onClick}>
            {button.label}
          </button>
        )}
      </For>
    </div>
  );
}
