// src/components/ColorControl.tsx
import { useState, useRef, useEffect } from 'react';

interface ColorControlProps {
  label: string;
  value: string;
  onChange: (value: string) => void;
}

const HEX_COLOR_REGEX = /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/;

export function ColorControl({ label, value, onChange }: ColorControlProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState(value);
  const colorInputRef = useRef<HTMLInputElement>(null);

  // Sync editValue when value changes externally
  useEffect(() => {
    if (!isEditing) {
      setEditValue(value);
    }
  }, [value, isEditing]);

  function handleTextSubmit() {
    setIsEditing(false);
    if (HEX_COLOR_REGEX.test(editValue)) {
      onChange(editValue);
    } else {
      setEditValue(value);
    }
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter') {
      handleTextSubmit();
    } else if (e.key === 'Escape') {
      setIsEditing(false);
      setEditValue(value);
    }
  }

  return (
    <div className="design-kit-color-control">
      <span className="design-kit-color-label">{label}</span>
      <div className="design-kit-color-inputs">
        {isEditing ? (
          <input
            type="text"
            className="design-kit-color-hex-input"
            value={editValue}
            onChange={(e) => setEditValue(e.target.value)}
            onBlur={handleTextSubmit}
            onKeyDown={handleKeyDown}
            autoFocus
          />
        ) : (
          <span
            className="design-kit-color-hex"
            onClick={() => setIsEditing(true)}
          >
            {(value ?? '').toUpperCase()}
          </span>
        )}
        <button
          className="design-kit-color-swatch"
          style={{ backgroundColor: value }}
          onClick={() => colorInputRef.current?.click()}
          title="Pick color"
        />
        <input
          ref={colorInputRef}
          type="color"
          className="design-kit-color-picker-native"
          value={value.length === 4 ? expandShorthandHex(value) : value.slice(0, 7)}
          onChange={(e) => onChange(e.target.value)}
        />
      </div>
    </div>
  );
}

function expandShorthandHex(hex: string): string {
  if (hex.length !== 4) return hex;
  return `#${hex[1]}${hex[1]}${hex[2]}${hex[2]}${hex[3]}${hex[3]}`;
}

// src/solid/components/ColorControl.tsx
import { createSignal, createEffect, createUniqueId, Show } from 'solid-js';

interface ColorControlProps {
  label: string;
  value: string;
  onChange: (value: string) => void;
}

const HEX_COLOR_REGEX = /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/;

function expandShorthandHex(hex: string): string {
  if (hex.length !== 4) return hex;
  return `#${hex[1]}${hex[1]}${hex[2]}${hex[2]}${hex[3]}${hex[3]}`;
}

export function ColorControl(props: ColorControlProps) {
  const [isEditing, setIsEditing] = createSignal(false);
  const [editValue, setEditValue] = createSignal(props.value);
  const textInputId = createUniqueId();
  let colorInputRef!: HTMLInputElement;

  // Sync editValue when value changes externally
  createEffect(() => {
    if (!isEditing()) {
      setEditValue(props.value);
    }
  });

  const handleTextSubmit = () => {
    setIsEditing(false);
    if (HEX_COLOR_REGEX.test(editValue())) {
      props.onChange(editValue());
    } else {
      setEditValue(props.value);
    }
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter') handleTextSubmit();
    else if (e.key === 'Escape') {
      setIsEditing(false);
      setEditValue(props.value);
    }
  };

  return (
    <div class="design-kit-color-control">
      <label class="design-kit-color-label" for={textInputId}>{props.label}</label>
      <div class="design-kit-color-inputs">
        <Show
          when={isEditing()}
          fallback={
            <span class="design-kit-color-hex" onClick={() => setIsEditing(true)}>
              {(props.value ?? '').toUpperCase()}
            </span>
          }
        >
          <input
            id={textInputId}
            type="text"
            class="design-kit-color-hex-input"
            value={editValue()}
            onInput={(e) => setEditValue(e.currentTarget.value)}
            onBlur={handleTextSubmit}
            onKeyDown={handleKeyDown}
            autofocus
          />
        </Show>
        <button
          class="design-kit-color-swatch"
          style={{ 'background-color': props.value }}
          onClick={() => colorInputRef?.click()}
          title="Pick color"
          aria-label={`Pick color for ${props.label}`}
        />
        <input
          ref={colorInputRef}
          type="color"
          class="design-kit-color-picker-native"
          aria-label={`${props.label} color picker`}
          value={props.value.length === 4 ? expandShorthandHex(props.value) : props.value.slice(0, 7)}
          onInput={(e) => props.onChange(e.currentTarget.value)}
        />
      </div>
    </div>
  );
}
