// src/solid/components/ColorControl.tsx
import { createSignal, createEffect, createUniqueId, Show } from 'solid-js';

interface ColorControlProps {
  label: string;
  value: string;
  onChange: (value: string) => void;
}

const HEX_COLOR_REGEX = /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/;

function expandShorthandHex(hex: string): string {
  if (hex.length !== 4) return hex;
  return `#${hex[1]}${hex[1]}${hex[2]}${hex[2]}${hex[3]}${hex[3]}`;
}

export function ColorControl(props: ColorControlProps) {
  const [isEditing, setIsEditing] = createSignal(false);
  const [editValue, setEditValue] = createSignal(props.value);
  const textInputId = createUniqueId();
  let colorInputRef!: HTMLInputElement;

  // Sync editValue when value changes externally
  createEffect(() => {
    if (!isEditing()) {
      setEditValue(props.value);
    }
  });

  const handleTextSubmit = () => {
    setIsEditing(false);
    if (HEX_COLOR_REGEX.test(editValue())) {
      props.onChange(editValue());
    } else {
      setEditValue(props.value);
    }
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter') handleTextSubmit();
    else if (e.key === 'Escape') {
      setIsEditing(false);
      setEditValue(props.value);
    }
  };

  return (
    <div class="design-kit-color-control">
      <label class="design-kit-color-label" for={textInputId}>{props.label}</label>
      <div class="design-kit-color-inputs">
        <Show
          when={isEditing()}
          fallback={
            <span class="design-kit-color-hex" onClick={() => setIsEditing(true)}>
              {(props.value ?? '').toUpperCase()}
            </span>
          }
        >
          <input
            id={textInputId}
            type="text"
            class="design-kit-color-hex-input"
            value={editValue()}
            onInput={(e) => setEditValue(e.currentTarget.value)}
            onBlur={handleTextSubmit}
            onKeyDown={handleKeyDown}
            autofocus
          />
        </Show>
        <button
          class="design-kit-color-swatch"
          style={{ 'background-color': props.value }}
          onClick={() => colorInputRef?.click()}
          title="Pick color"
          aria-label={`Pick color for ${props.label}`}
        />
        <input
          ref={colorInputRef}
          type="color"
          class="design-kit-color-picker-native"
          aria-label={`${props.label} color picker`}
          value={props.value.length === 4 ? expandShorthandHex(props.value) : props.value.slice(0, 7)}
          onInput={(e) => props.onChange(e.currentTarget.value)}
        />
      </div>
    </div>
  );
}

// src/svelte/components/ColorControl.svelte
<script lang="ts">
  const HEX_COLOR_REGEX = /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/;

  let { label, value, onChange } = $props<{
    label: string;
    value: string;
    onChange: (value: string) => void;
  }>();

  let isEditing = $state(false);
  let editValue = $state(value);
  let colorInputRef: HTMLInputElement | undefined;

  const expandShorthandHex = (hex: string) => {
    if (hex.length !== 4) return hex;
    return `#${hex[1]}${hex[1]}${hex[2]}${hex[2]}${hex[3]}${hex[3]}`;
  };

  $effect(() => {
    value;
    if (!isEditing) {
      editValue = value;
    }
  });

  const handleTextSubmit = () => {
    isEditing = false;
    if (HEX_COLOR_REGEX.test(editValue)) {
      onChange(editValue);
    } else {
      editValue = value;
    }
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleTextSubmit();
    } else if (e.key === 'Escape') {
      isEditing = false;
      editValue = value;
    }
  };
</script>

<div class="design-kit-color-control">
  <label class="design-kit-color-label">{label}</label>
  <div class="design-kit-color-inputs">
    {#if isEditing}
      <input
        type="text"
        class="design-kit-color-hex-input"
        value={editValue}
        oninput={(e) => (editValue = (e.currentTarget as HTMLInputElement).value)}
        onblur={handleTextSubmit}
        onkeydown={handleKeyDown}
        autofocus
      />
    {:else}
      <span class="design-kit-color-hex" onclick={() => (isEditing = true)}>
        {(value ?? '').toUpperCase()}
      </span>
    {/if}

    <button
      class="design-kit-color-swatch"
      style:background-color={value}
      onclick={() => colorInputRef?.click()}
      title="Pick color"
      aria-label={`Pick color for ${label}`}
    />

    <input
      bind:this={colorInputRef}
      type="color"
      class="design-kit-color-picker-native"
      aria-label={`${label} color picker`}
      value={value.length === 4 ? expandShorthandHex(value) : value.slice(0, 7)}
      oninput={(e) => onChange((e.currentTarget as HTMLInputElement).value)}
    />
  </div>
</div>
