// src/components/Folder.tsx
import { useState, useRef, useEffect, ReactNode } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ICON_PANEL, ICON_CHEVRON } from '../icons';

interface FolderProps {
  title: string;
  children: ReactNode;
  defaultOpen?: boolean;
  isRoot?: boolean;
  inline?: boolean;
  onOpenChange?: (isOpen: boolean) => void;
  toolbar?: ReactNode;
}

export function Folder({ title, children, defaultOpen = true, isRoot = false, inline = false, onOpenChange, toolbar }: FolderProps) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  const [isCollapsed, setIsCollapsed] = useState(!defaultOpen);
  const contentRef = useRef<HTMLDivElement>(null);
  const [contentHeight, setContentHeight] = useState<number | undefined>(undefined);
  const [windowHeight, setWindowHeight] = useState(typeof window !== 'undefined' ? window.innerHeight : 800);

  useEffect(() => {
    if (!isRoot) return;
    const onResize = () => setWindowHeight(window.innerHeight);
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, [isRoot]);

  // Track content height for explicit panel sizing (no height: 'auto')
  useEffect(() => {
    const el = contentRef.current;
    if (!el) return;
    const ro = new ResizeObserver(() => {
      if (isOpen) {
        const h = el.offsetHeight;
        setContentHeight(prev => prev === h ? prev : h);
      }
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, [isOpen]);

  const handleToggle = () => {
    if (inline && isRoot) return;
    const next = !isOpen;
    setIsOpen(next);
    if (next) {
      setIsCollapsed(false);
    } else {
      setIsCollapsed(true);
    }
    onOpenChange?.(next);
  };

  const folderContent = (
    <div ref={isRoot ? contentRef : undefined} className={`design-kit-folder ${isRoot ? 'design-kit-folder-root' : ''}`}>
      <div className={`design-kit-folder-header ${isRoot ? 'design-kit-panel-header' : ''}`} onClick={handleToggle}>
        <div className="design-kit-folder-header-top">
          {isRoot ? (
            isOpen && (
              <div className="design-kit-folder-title-row">
                <span className="design-kit-folder-title design-kit-folder-title-root">
                  {title}
                </span>
              </div>
            )
          ) : (
            <div className="design-kit-folder-title-row">
              <span className="design-kit-folder-title">
                {title}
              </span>
            </div>
          )}
          {isRoot && !inline && (
            <svg
              className="design-kit-panel-icon"
              viewBox="0 0 16 16"
              fill="none"
            >
              <path opacity="0.5" d={ICON_PANEL.path} fill="currentColor"/>
              {ICON_PANEL.circles.map((c, i) => (
                <circle key={i} cx={c.cx} cy={c.cy} r={c.r} fill="currentColor" stroke="currentColor" strokeWidth="1.25"/>
              ))}
            </svg>
          )}
          {!isRoot && (
            <motion.svg
              className="design-kit-folder-icon"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              initial={false}
              animate={{ rotate: isOpen ? 0 : 180 }}
              transition={{ type: 'spring', visualDuration: 0.35, bounce: 0.15 }}
            >
              <path d={ICON_CHEVRON} />
            </motion.svg>
          )}
        </div>

        {isRoot && toolbar && isOpen && (
          <div className="design-kit-panel-toolbar" onClick={(e) => e.stopPropagation()}>
            {toolbar}
          </div>
        )}
      </div>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            className="design-kit-folder-content"
            initial={isRoot ? undefined : { height: 0, opacity: 0 }}
            animate={isRoot ? undefined : { height: 'auto', opacity: 1 }}
            exit={isRoot ? undefined : { height: 0, opacity: 0 }}
            transition={isRoot ? undefined : { type: 'spring', visualDuration: 0.35, bounce: 0.1 }}
            style={isRoot ? undefined : { clipPath: 'inset(0 -20px)' }}
          >
            <div className="design-kit-folder-inner">{children}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );

  if (isRoot) {
    if (inline) {
      return (
        <div className="design-kit-panel-inner design-kit-panel-inline">
          {folderContent}
        </div>
      );
    }

    const panelStyle = isOpen
      ? { width: 280, height: contentHeight !== undefined ? Math.min(contentHeight + 10, windowHeight - 32) : 'auto' as const, borderRadius: 14, boxShadow: 'var(--dial-shadow)', cursor: undefined as string | undefined, overflowY: 'auto' as const }
      : { width: 42, height: 42, borderRadius: '50%', boxSizing: 'border-box' as const, boxShadow: 'var(--dial-shadow-collapsed)', overflow: 'hidden' as const, cursor: 'pointer' as const };

    return (
      <motion.div
        className="design-kit-panel-inner"
        style={panelStyle}
        onClick={!isOpen ? handleToggle : undefined}
        data-collapsed={isCollapsed}
        whileTap={!isOpen ? { scale: 0.9 } : undefined}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        {folderContent}
      </motion.div>
    );
  }

  return folderContent;
}

// src/svelte/components/Folder.svelte
<script lang="ts">
  import { Spring } from 'svelte/motion';
  import { slide } from 'svelte/transition';

  import type { Snippet } from 'svelte';
  import { ICON_PANEL, ICON_CHEVRON } from '../../icons';

  let {
    title,
    defaultOpen = true,
    isRoot = false,
    inline = false,
    onOpenChange,
    toolbar,
    children,
  } = $props<{
    title: string;
    defaultOpen?: boolean;
    isRoot?: boolean;
    inline?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
    toolbar?: Snippet;
    children?: Snippet;
  }>();

  let isOpen = $state(defaultOpen);
  let isCollapsed = $state(!defaultOpen);
  let contentHeight = $state<number | undefined>(undefined);

  let contentRef: HTMLDivElement | undefined;
  let panelRef: HTMLDivElement | undefined;
  let windowHeight = $state(typeof window !== 'undefined' ? window.innerHeight : 800);

  $effect(() => {
    if (!isRoot) return;
    const onResize = () => { windowHeight = window.innerHeight; };
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  });

  const chevronRotation = new Spring(defaultOpen ? 0 : 180, { stiffness: 0.2, damping: 0.6 });
  const panelWidth = new Spring(defaultOpen ? 280 : 42, { stiffness: 0.2, damping: 0.62 });
  const panelHeight = new Spring(defaultOpen ? 220 : 42, { stiffness: 0.2, damping: 0.62 });
  const panelRadius = new Spring(defaultOpen ? 14 : 21, { stiffness: 0.2, damping: 0.62 });
  const panelScale = new Spring(1, { stiffness: 0.25, damping: 0.7 });

  $effect(() => {
    if (!isRoot || !contentRef || typeof ResizeObserver === 'undefined') return;

    const ro = new ResizeObserver(() => {
      if (!isOpen) return;
      const next = contentRef?.offsetHeight;
      if (!next) return;
      contentHeight = next;
    });

    ro.observe(contentRef);

    if (contentRef.offsetHeight > 0) {
      contentHeight = contentRef.offsetHeight;
    }

    return () => {
      ro.disconnect();
    };
  });

  $effect(() => {
    if (isRoot) return;
    chevronRotation.set(isOpen ? 0 : 180);
  });

  $effect(() => {
    if (!isRoot) return;

    const measured = contentHeight ?? panelRef?.getBoundingClientRect().height ?? 42;
    const nextHeight = isOpen ? Math.min(measured + 10, windowHeight - 32) : 42;

    panelWidth.set(isOpen ? 280 : 42);
    panelHeight.set(nextHeight);
    panelRadius.set(isOpen ? 14 : 21);
  });

  const handleToggle = () => {
    if (inline && isRoot) return;
    const next = !isOpen;
    isOpen = next;
    isCollapsed = !next;
    onOpenChange?.(next);
  };

  const handleCollapsedTapStart = () => {
    if (isOpen) return;
    (document.activeElement as HTMLElement | null)?.blur?.();
    panelScale.set(0.9);
  };

  const handleCollapsedTapEnd = () => {
    if (isOpen) return;
    panelScale.set(1);
  };

  const panelStyle = $derived(
    `width:${panelWidth.current}px;height:${panelHeight.current}px;border-radius:${panelRadius.current}px;` +
      `box-shadow:${isOpen ? 'var(--dial-shadow)' : 'var(--dial-shadow-collapsed)'};` +
      `cursor:${isOpen ? '' : 'pointer'};overflow:${isOpen ? 'hidden auto' : 'hidden'};` +
      `transform:scale(${panelScale.current});`
  );
</script>

{#if isRoot && inline}
  <div class="design-kit-panel-inner design-kit-panel-inline">
    <div bind:this={contentRef} class="design-kit-folder design-kit-folder-root">
      <div class="design-kit-folder-header design-kit-panel-header" onclick={(e) => { e.stopPropagation(); handleToggle(); }}>
        <div class="design-kit-folder-header-top">
          <div class="design-kit-folder-title-row">
            <span class="design-kit-folder-title design-kit-folder-title-root">{title}</span>
          </div>
        </div>

        <div class="design-kit-panel-toolbar" onclick={(e) => e.stopPropagation()}>
          {#if toolbar}{@render toolbar()}{/if}
        </div>
      </div>

      <div class="design-kit-folder-content">
        <div class="design-kit-folder-inner">
          {#if children}{@render children()}{/if}
        </div>
      </div>
    </div>
  </div>
{:else if isRoot}
  <div
    bind:this={panelRef}
    class="design-kit-panel-inner"
    data-collapsed={String(isCollapsed)}
    style={panelStyle}
    onpointerdown={handleCollapsedTapStart}
    onpointerup={handleCollapsedTapEnd}
    onpointercancel={handleCollapsedTapEnd}
    onpointerleave={handleCollapsedTapEnd}
    onclick={() => { if (!isOpen) handleToggle(); }}
  >
    <div bind:this={contentRef} class="design-kit-folder design-kit-folder-root">
      <div class="design-kit-folder-header design-kit-panel-header" onclick={(e) => { e.stopPropagation(); handleToggle(); }}>
        <div class="design-kit-folder-header-top">
          {#if isOpen}
            <div class="design-kit-folder-title-row">
              <span class="design-kit-folder-title design-kit-folder-title-root">{title}</span>
            </div>
          {/if}

          <svg class="design-kit-panel-icon" viewBox="0 0 16 16" fill="none">
            <path
              opacity="0.5"
              d={ICON_PANEL.path}
              fill="currentColor"
            />
            <circle cx={ICON_PANEL.circles[0].cx} cy={ICON_PANEL.circles[0].cy} r={ICON_PANEL.circles[0].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
            <circle cx={ICON_PANEL.circles[1].cx} cy={ICON_PANEL.circles[1].cy} r={ICON_PANEL.circles[1].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
            <circle cx={ICON_PANEL.circles[2].cx} cy={ICON_PANEL.circles[2].cy} r={ICON_PANEL.circles[2].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
          </svg>
        </div>

        {#if isOpen}
          <div class="design-kit-panel-toolbar" onclick={(e) => e.stopPropagation()}>
            {#if toolbar}{@render toolbar()}{/if}
          </div>
        {/if}
      </div>

      {#if isOpen}
        <div class="design-kit-folder-content">
          <div class="design-kit-folder-inner">
            {#if children}{@render children()}{/if}
          </div>
        </div>
      {/if}
    </div>
  </div>
{:else}
  <div class="design-kit-folder">
    <div class="design-kit-folder-header" onclick={handleToggle}>
      <div class="design-kit-folder-header-top">
        <div class="design-kit-folder-title-row">
          <span class="design-kit-folder-title">{title}</span>
        </div>

        <svg
          class="design-kit-folder-icon"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.5"
          stroke-linecap="round"
          stroke-linejoin="round"
          style:transform={`rotate(${chevronRotation.current}deg)`}
        >
          <path d={ICON_CHEVRON} />
        </svg>
      </div>
    </div>

    {#if isOpen}
      <div class="design-kit-folder-content" style="clip-path: inset(0 -20px);" transition:slide={{ duration: 220 }}>
        <div class="design-kit-folder-inner">
          {#if children}{@render children()}{/if}
        </div>
      </div>
    {/if}
  </div>
{/if}
