// src/solid/components/Panel.tsx
import { createSignal, createEffect, onMount, onCleanup, Show, For, JSX } from 'solid-js';
import { animate } from 'motion';
import { ICON_CLIPBOARD, ICON_CHECK, ICON_ADD_PRESET } from '../../icons';
import { DesignKitStore } from '../../store/DesignKitStore';
import type { ControlMeta, PanelConfig, SpringConfig, DesignValue } from '../../store/DesignKitStore';
import { useShortcutContext } from './ShortcutListener';
import { ShortcutsMenu } from './ShortcutsMenu';
import { Folder } from './Folder';
import { Slider } from './Slider';
import { Toggle } from './Toggle';
import { SpringControl } from './SpringControl';
import { TextControl } from './TextControl';
import { SelectControl } from './SelectControl';
import { ColorControl } from './ColorControl';
import { PresetManager } from './PresetManager';

interface PanelProps {
  panel: PanelConfig;
  defaultOpen?: boolean;
  inline?: boolean;
}

export function Panel(props: PanelProps) {
  const [copied, setCopied] = createSignal(false);
  const [isPanelOpen, setIsPanelOpen] = createSignal(props.defaultOpen ?? true);
  const shortcutCtx = useShortcutContext();
  const hasShortcuts = () => Object.keys(props.panel.shortcuts).length > 0;
  const [values, setValues] = createSignal<Record<string, DesignValue>>(
    DesignKitStore.getValues(props.panel.id)
  );
  const [presets, setPresets] = createSignal(DesignKitStore.getPresets(props.panel.id));
  const [activePresetId, setActivePresetId] = createSignal(DesignKitStore.getActivePresetId(props.panel.id));
  let addButtonRef!: HTMLButtonElement;
  let copyButtonRef!: HTMLButtonElement;
  let copyClipboardIconRef!: HTMLSpanElement;
  let copyCheckIconRef!: HTMLSpanElement;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let addTapAnim: any = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let copyTapAnim: any = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let copyClipboardAnim: any = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let copyCheckAnim: any = null;
  let didInitCopyIcons = false;

  const tapTransition = { type: 'spring' as const, visualDuration: 0.15, bounce: 0.3 };

  onMount(() => {
    const unsub = DesignKitStore.subscribe(props.panel.id, () => {
      setValues(DesignKitStore.getValues(props.panel.id));
      setPresets(DesignKitStore.getPresets(props.panel.id));
      setActivePresetId(DesignKitStore.getActivePresetId(props.panel.id));
    });

    if (copyClipboardIconRef && copyCheckIconRef) {
      copyClipboardIconRef.style.transformOrigin = '50% 50%';
      copyClipboardIconRef.style.opacity = '1';
      copyClipboardIconRef.style.transform = 'scale(1)';
      copyClipboardIconRef.style.filter = 'blur(0px)';
      copyCheckIconRef.style.transformOrigin = '50% 50%';
      copyCheckIconRef.style.opacity = '0';
      copyCheckIconRef.style.transform = 'scale(0.5)';
      copyCheckIconRef.style.filter = 'blur(4px)';
      didInitCopyIcons = true;
    }

    onCleanup(unsub);
  });

  const handleAddPreset = () => {
    const nextNum = presets().length + 2;
    DesignKitStore.savePreset(props.panel.id, `Version ${nextNum}`);
  };

  const handleCopy = () => {
    const jsonStr = JSON.stringify(values(), null, 2);
    const instruction = `Update the createDesignKit configuration for "${props.panel.name}" with these values:\n\n\`\`\`json\n${jsonStr}\n\`\`\`\n\nApply these values as the new defaults in the createDesignKit call.`;
    navigator.clipboard.writeText(instruction);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  createEffect(() => {
    const isCopied = copied();
    if (!copyClipboardIconRef || !copyCheckIconRef) return;

    copyClipboardAnim?.stop();
    copyCheckAnim?.stop();

    if (!didInitCopyIcons) return;

    const transition = { type: 'spring' as const, visualDuration: 0.3, bounce: 0.2 };
    copyClipboardAnim = animate(copyClipboardIconRef, {
      opacity: isCopied ? 0 : 1,
      scale: isCopied ? 0.5 : 1,
      filter: isCopied ? 'blur(4px)' : 'blur(0px)',
    }, transition);
    copyCheckAnim = animate(copyCheckIconRef, {
      opacity: isCopied ? 1 : 0,
      scale: isCopied ? 1 : 0.5,
      filter: isCopied ? 'blur(0px)' : 'blur(4px)',
    }, transition);
  });

  onCleanup(() => {
    addTapAnim?.stop();
    copyTapAnim?.stop();
    copyClipboardAnim?.stop();
    copyCheckAnim?.stop();
  });

  const handleAddTapStart = () => {
    if (!addButtonRef) return;
    addTapAnim?.stop();
    addTapAnim = animate(addButtonRef, { scale: 0.9 }, tapTransition);
  };

  const handleAddTapEnd = () => {
    if (!addButtonRef) return;
    addTapAnim?.stop();
    addTapAnim = animate(addButtonRef, { scale: 1 }, tapTransition);
  };

  const handleCopyTapStart = () => {
    if (!copyButtonRef) return;
    copyTapAnim?.stop();
    copyTapAnim = animate(copyButtonRef, { scale: 0.95 }, tapTransition);
  };

  const handleCopyTapEnd = () => {
    if (!copyButtonRef) return;
    copyTapAnim?.stop();
    copyTapAnim = animate(copyButtonRef, { scale: 1 }, tapTransition);
  };

  const renderControl = (control: ControlMeta) => {
    const value = () => values()[control.path];

    switch (control.type) {
      case 'slider':
        return (
          <Slider
            label={control.label}
            value={value() as number}
            onChange={(v) => DesignKitStore.updateValue(props.panel.id, control.path, v)}
            min={control.min}
            max={control.max}
            step={control.step}
            shortcut={control.shortcut}
            shortcutActive={shortcutCtx().activePanelId === props.panel.id && shortcutCtx().activePath === control.path}
          />
        );

      case 'toggle':
        return (
          <Toggle
            label={control.label}
            checked={value() as boolean}
            onChange={(v) => DesignKitStore.updateValue(props.panel.id, control.path, v)}
            shortcut={control.shortcut}
            shortcutActive={shortcutCtx().activePanelId === props.panel.id && shortcutCtx().activePath === control.path}
          />
        );

      case 'spring':
        return (
          <SpringControl
            panelId={props.panel.id}
            path={control.path}
            label={control.label}
            spring={value() as SpringConfig}
            onChange={(v) => DesignKitStore.updateValue(props.panel.id, control.path, v)}
          />
        );

      case 'folder':
        return (
          <Folder title={control.label} defaultOpen={control.defaultOpen ?? true}>
            <For each={control.children ?? []}>
              {(child) => <>{renderControl(child)}</>}
            </For>
          </Folder>
        );

      case 'text':
        return (
          <TextControl
            label={control.label}
            value={value() as string}
            onChange={(v) => DesignKitStore.updateValue(props.panel.id, control.path, v)}
            placeholder={control.placeholder}
          />
        );

      case 'select':
        return (
          <SelectControl
            label={control.label}
            value={value() as string}
            options={control.options ?? []}
            onChange={(v) => DesignKitStore.updateValue(props.panel.id, control.path, v)}
          />
        );

      case 'color':
        return (
          <ColorControl
            label={control.label}
            value={value() as string}
            onChange={(v) => DesignKitStore.updateValue(props.panel.id, control.path, v)}
          />
        );

      default:
        return null;
    }
  };

  const renderControls = () => {
    return (
      <For each={props.panel.controls}>
        {(control) => (
          <>
            {control.type === 'action' ? (
              <button
                class="design-kit-button"
                onClick={() => DesignKitStore.triggerAction(props.panel.id, control.path)}
              >
                {control.label}
              </button>
            ) : (
              renderControl(control)
            )}
          </>
        )}
      </For>
    );
  };

  const toolbar = (
    <>
      <button
        ref={addButtonRef}
        class="design-kit-toolbar-add"
        onClick={handleAddPreset}
        onPointerDown={handleAddTapStart}
        onPointerUp={handleAddTapEnd}
        onPointerCancel={handleAddTapEnd}
        onPointerLeave={handleAddTapEnd}
        title="Add preset"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <path d={ICON_ADD_PRESET[0]} />
          <path d={ICON_ADD_PRESET[1]} />
          <path d={ICON_ADD_PRESET[2]} />
          <path d={ICON_ADD_PRESET[3]} />
          <path d={ICON_ADD_PRESET[4]} />
        </svg>
      </button>

      <PresetManager
        panelId={props.panel.id}
        presets={presets()}
        activePresetId={activePresetId()}
        onAdd={handleAddPreset}
      />

      <button
        ref={copyButtonRef}
        class="design-kit-toolbar-copy"
        onClick={handleCopy}
        onPointerDown={handleCopyTapStart}
        onPointerUp={handleCopyTapEnd}
        onPointerCancel={handleCopyTapEnd}
        onPointerLeave={handleCopyTapEnd}
        title="Copy parameters"
      >
        <span class="design-kit-toolbar-copy-icon-wrap">
          <span
            ref={copyClipboardIconRef}
            class="design-kit-toolbar-copy-icon"
            style={{ opacity: 1, transform: 'scale(1)', filter: 'blur(0px)' }}
          >
            <svg viewBox="0 0 24 24" fill="none" width="16" height="16">
              <path d={ICON_CLIPBOARD.board} stroke="currentColor" stroke-width="2" stroke-linejoin="round" />
              <path d={ICON_CLIPBOARD.sparkle} fill="currentColor" />
              <path d={ICON_CLIPBOARD.body} stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </span>
          <span
            ref={copyCheckIconRef}
            class="design-kit-toolbar-copy-icon"
            style={{ opacity: 0, transform: 'scale(0.5)', filter: 'blur(4px)' }}
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="16" height="16">
              <path d={ICON_CHECK} />
            </svg>
          </span>
        </span>
        Copy
      </button>

    </>
  );

  return (
    <div class="design-kit-panel-wrapper">
      <Folder title={props.panel.name} defaultOpen={props.defaultOpen ?? true} isRoot={true} inline={props.inline ?? false} onOpenChange={setIsPanelOpen} toolbar={toolbar}>
        {renderControls()}
      </Folder>
    </div>
  );
}

// src/svelte/components/Panel.svelte
<script lang="ts">
  import { Spring } from 'svelte/motion';
  import { DesignKitStore } from 'design-kit/store';
  import type { DesignValue, PanelConfig, Preset } from 'design-kit/store';
  import Folder from './Folder.svelte';
  import PresetManager from './PresetManager.svelte';
  import ControlRenderer from './ControlRenderer.svelte';
  import ShortcutsMenu from './ShortcutsMenu.svelte';
  import { ICON_CLIPBOARD, ICON_CHECK, ICON_ADD_PRESET } from '../../icons';

  let { panel, defaultOpen = true, inline = false } = $props<{ panel: PanelConfig; defaultOpen?: boolean; inline?: boolean }>();

  const hasShortcuts = $derived(Object.keys(panel.shortcuts).length > 0);

  let copied = $state(false);
  let isPanelOpen = $state(defaultOpen);
  let values = $state<Record<string, DesignValue>>(DesignKitStore.getValues(panel.id));
  let presets = $state<Preset[]>(DesignKitStore.getPresets(panel.id));
  let activePresetId = $state<string | null>(DesignKitStore.getActivePresetId(panel.id));

  const addScale = new Spring(1, { stiffness: 0.25, damping: 0.7 });
  const copyScale = new Spring(1, { stiffness: 0.25, damping: 0.7 });
  const clipboardOpacity = new Spring(1, { stiffness: 0.25, damping: 0.7 });
  const clipboardScale = new Spring(1, { stiffness: 0.2, damping: 0.6 });
  const checkOpacity = new Spring(0, { stiffness: 0.25, damping: 0.7 });
  const checkScale = new Spring(0.5, { stiffness: 0.2, damping: 0.6 });

  let copyTimeout: ReturnType<typeof setTimeout> | undefined;

  $effect(() => {
    const unsub = DesignKitStore.subscribe(panel.id, () => {
      values = DesignKitStore.getValues(panel.id);
      presets = DesignKitStore.getPresets(panel.id);
      activePresetId = DesignKitStore.getActivePresetId(panel.id);
    });

    return () => {
      unsub();
      if (copyTimeout) clearTimeout(copyTimeout);
    };
  });

  $effect(() => {
    if (copied) {
      clipboardOpacity.set(0);
      clipboardScale.set(0.5);
      checkOpacity.set(1);
      checkScale.set(1);
      return;
    }

    clipboardOpacity.set(1);
    clipboardScale.set(1);
    checkOpacity.set(0);
    checkScale.set(0.5);
  });

  const handleAddPreset = () => {
    const nextNum = presets.length + 2;
    DesignKitStore.savePreset(panel.id, `Version ${nextNum}`);
  };

  const handleCopy = async () => {
    const jsonStr = JSON.stringify(values, null, 2);
    const instruction = `Update the createDesignKit configuration for "${panel.name}" with these values:\n\n\`\`\`json\n${jsonStr}\n\`\`\`\n\nApply these values as the new defaults in the createDesignKit call.`;

    await navigator.clipboard.writeText(instruction);
    copied = true;

    if (copyTimeout) clearTimeout(copyTimeout);
    copyTimeout = setTimeout(() => {
      copied = false;
    }, 1500);
  };
</script>

<div class="design-kit-panel-wrapper">
  <Folder title={panel.name} {defaultOpen} isRoot={true} {inline} onOpenChange={(open) => (isPanelOpen = open)}>
    {#snippet toolbar()}
      <button
        class="design-kit-toolbar-add"
        onclick={handleAddPreset}
        onpointerdown={() => addScale.set(0.9)}
        onpointerup={() => addScale.set(1)}
        onpointercancel={() => addScale.set(1)}
        onpointerleave={() => addScale.set(1)}
        title="Add preset"
        style:transform={`scale(${addScale.current})`}
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <path d={ICON_ADD_PRESET[0]} />
          <path d={ICON_ADD_PRESET[1]} />
          <path d={ICON_ADD_PRESET[2]} />
          <path d={ICON_ADD_PRESET[3]} />
          <path d={ICON_ADD_PRESET[4]} />
        </svg>
      </button>

      <PresetManager panelId={panel.id} {presets} {activePresetId} />

      <button
        class="design-kit-toolbar-copy"
        onclick={handleCopy}
        onpointerdown={() => copyScale.set(0.95)}
        onpointerup={() => copyScale.set(1)}
        onpointercancel={() => copyScale.set(1)}
        onpointerleave={() => copyScale.set(1)}
        title="Copy parameters"
        style:transform={`scale(${copyScale.current})`}
      >
        <span class="design-kit-toolbar-copy-icon-wrap">
          <svg
            class="design-kit-toolbar-copy-icon"
            viewBox="0 0 24 24"
            fill="none"
            style:opacity={clipboardOpacity.current}
            style:transform={`scale(${clipboardScale.current})`}
            style:filter={`blur(${(1 - clipboardOpacity.current) * 4}px)`}
          >
            <path d={ICON_CLIPBOARD.board} stroke="currentColor" stroke-width="2" stroke-linejoin="round"/>
            <path d={ICON_CLIPBOARD.sparkle} fill="currentColor"/>
            <path d={ICON_CLIPBOARD.body} stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>

          <svg
            class="design-kit-toolbar-copy-icon"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            style:opacity={checkOpacity.current}
            style:transform={`scale(${checkScale.current})`}
            style:filter={`blur(${(1 - checkOpacity.current) * 4}px)`}
          >
            <path d={ICON_CHECK} />
          </svg>
        </span>
        Copy
      </button>

    {/snippet}

    {#each panel.controls as control (control.path)}
      <ControlRenderer panelId={panel.id} {control} {values} />
    {/each}
  </Folder>
</div>
