// src/components/ShortcutsMenu.tsx
import { useState, useRef, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'motion/react';
import { DesignKitStore, ShortcutConfig } from '../store/DesignKitStore';

interface ShortcutsMenuProps {
  panelId: string;
}

function formatShortcutKey(sc: ShortcutConfig): string {
  if (!sc.key) return '—';
  const mod = sc.modifier === 'alt' ? '⌥'
    : sc.modifier === 'shift' ? '⇧'
    : sc.modifier === 'meta' ? '⌘'
    : '';
  return `${mod}${sc.key.toUpperCase()}`;
}

function formatInteraction(sc: ShortcutConfig): string {
  const interaction = sc.interaction ?? 'scroll';
  switch (interaction) {
    case 'scroll': return sc.key ? 'key+scroll' : 'scroll';
    case 'drag': return 'key+drag';
    case 'move': return 'key+move';
    case 'scroll-only': return 'scroll';
  }
}

export function ShortcutsMenu({ panelId }: ShortcutsMenuProps) {
  const [isOpen, setIsOpen] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const [pos, setPos] = useState({ top: 0, right: 0 });

  const open = useCallback(() => {
    const rect = triggerRef.current?.getBoundingClientRect();
    if (rect) {
      setPos({ top: rect.bottom + 4, right: window.innerWidth - rect.right });
    }
    setIsOpen(true);
  }, []);

  const close = useCallback(() => setIsOpen(false), []);

  const toggle = useCallback(() => {
    if (isOpen) close();
    else open();
  }, [isOpen, open, close]);

  // Close on mousedown outside
  useEffect(() => {
    if (!isOpen) return;

    const handler = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        triggerRef.current?.contains(target) ||
        dropdownRef.current?.contains(target)
      ) return;
      close();
    };

    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [isOpen, close]);

  const panel = DesignKitStore.getPanel(panelId);
  if (!panel) return null;

  const shortcuts = Object.entries(panel.shortcuts);
  if (shortcuts.length === 0) return null;

  // Build shortcut rows with labels from controls
  const rows = shortcuts.map(([path, shortcut]) => {
    // Find control label
    const findLabel = (controls: typeof panel.controls): string => {
      for (const c of controls) {
        if (c.path === path) return c.label;
        if (c.type === 'folder' && c.children) {
          const found = findLabel(c.children);
          if (found) return found;
        }
      }
      return path;
    };
    return {
      path,
      shortcut,
      label: findLabel(panel.controls),
    };
  });

  return (
    <>
      <motion.button
        ref={triggerRef}
        className="design-kit-shortcuts-trigger"
        onClick={toggle}
        title="Keyboard shortcuts"
        whileTap={{ scale: 0.9 }}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <rect x="2" y="6" width="20" height="12" rx="2" />
          <path d="M6 10H6.01" />
          <path d="M10 10H10.01" />
          <path d="M14 10H14.01" />
          <path d="M18 10H18.01" />
          <path d="M8 14H16" />
        </svg>
      </motion.button>

      {createPortal(
        <AnimatePresence>
          {isOpen && (
            <motion.div
              ref={dropdownRef}
              className="design-kit-root design-kit-shortcuts-dropdown"
              style={{ position: 'fixed', top: pos.top, right: pos.right }}
              initial={{ opacity: 0, y: 4, scale: 0.97 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 4, scale: 0.97, pointerEvents: 'none' as any }}
              transition={{ type: 'spring', visualDuration: 0.15, bounce: 0 }}
            >
              <div className="design-kit-shortcuts-title">Keyboard Shortcuts</div>
              <div className="design-kit-shortcuts-list">
                {rows.map((row) => (
                  <div key={row.path} className="design-kit-shortcuts-row">
                    <span className="design-kit-shortcuts-row-key">
                      {formatShortcutKey(row.shortcut)}
                    </span>
                    <span className="design-kit-shortcuts-row-label">{row.label}</span>
                    <span className="design-kit-shortcuts-row-mode">{formatInteraction(row.shortcut)}</span>
                  </div>
                ))}
              </div>
              <div className="design-kit-shortcuts-hint">See pill badges on controls for keys</div>
            </motion.div>
          )}
        </AnimatePresence>,
        document.body
      )}
    </>
  );
}

// src/svelte/components/ShortcutsMenu.svelte
<script lang="ts">
  import { DesignKitStore } from 'design-kit/store';
  import type { ShortcutConfig } from 'design-kit/store';
  import Portal from '../Portal.svelte';

  let { panelId } = $props<{ panelId: string }>();

  let isOpen = $state(false);
  let triggerEl: HTMLButtonElement | undefined;
  let dropdownEl: HTMLDivElement | undefined;
  let pos = $state({ top: 0, right: 0 });

  function formatShortcutKey(sc: ShortcutConfig): string {
    if (!sc.key) return '\u2014';
    const mod = sc.modifier === 'alt' ? '\u2325'
      : sc.modifier === 'shift' ? '\u21E7'
      : sc.modifier === 'meta' ? '\u2318'
      : '';
    return `${mod}${sc.key.toUpperCase()}`;
  }

  function formatInteraction(sc: ShortcutConfig): string {
    const interaction = sc.interaction ?? 'scroll';
    switch (interaction) {
      case 'scroll': return sc.key ? 'key+scroll' : 'scroll';
      case 'drag': return 'key+drag';
      case 'move': return 'key+move';
      case 'scroll-only': return 'scroll';
    }
  }

  function open() {
    const rect = triggerEl?.getBoundingClientRect();
    if (rect) {
      pos = { top: rect.bottom + 4, right: window.innerWidth - rect.right };
    }
    isOpen = true;
  }

  function close() {
    isOpen = false;
  }

  function toggle() {
    if (isOpen) close();
    else open();
  }

  // Close on mousedown outside
  $effect(() => {
    if (!isOpen) return;

    const handler = (e: MouseEvent) => {
      const target = e.target as Node;
      if (triggerEl?.contains(target) || dropdownEl?.contains(target)) return;
      close();
    };

    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  });

  const panel = $derived(DesignKitStore.getPanel(panelId));

  const rows = $derived.by(() => {
    if (!panel) return [];
    const shortcuts = Object.entries(panel.shortcuts);
    if (shortcuts.length === 0) return [];

    return shortcuts.map(([path, shortcut]) => {
      const findLabel = (controls: typeof panel.controls): string => {
        for (const c of controls) {
          if (c.path === path) return c.label;
          if (c.type === 'folder' && c.children) {
            const found = findLabel(c.children);
            if (found) return found;
          }
        }
        return path;
      };
      return { path, shortcut, label: findLabel(panel.controls) };
    });
  });
</script>

{#if panel && rows.length > 0}
  <button
    bind:this={triggerEl}
    class="design-kit-shortcuts-trigger"
    onclick={toggle}
    title="Keyboard shortcuts"
  >
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <rect x="2" y="6" width="20" height="12" rx="2" />
      <path d="M6 10H6.01" />
      <path d="M10 10H10.01" />
      <path d="M14 10H14.01" />
      <path d="M18 10H18.01" />
      <path d="M8 14H16" />
    </svg>
  </button>

  <Portal target="body">
    {#if isOpen}
      <div
        bind:this={dropdownEl}
        class="design-kit-root design-kit-shortcuts-dropdown"
        style:position="fixed"
        style:top="{pos.top}px"
        style:right="{pos.right}px"
      >
        <div class="design-kit-shortcuts-title">Keyboard Shortcuts</div>
        <div class="design-kit-shortcuts-list">
          {#each rows as row (row.path)}
            <div class="design-kit-shortcuts-row">
              <span class="design-kit-shortcuts-row-key">
                {formatShortcutKey(row.shortcut)}
              </span>
              <span class="design-kit-shortcuts-row-label">{row.label}</span>
              <span class="design-kit-shortcuts-row-mode">{formatInteraction(row.shortcut)}</span>
            </div>
          {/each}
        </div>
        <div class="design-kit-shortcuts-hint">See pill badges on controls for keys</div>
      </div>
    {/if}
  </Portal>
{/if}
