// src/solid/components/SpringControl.tsx
import { createSignal, onMount, onCleanup } from 'solid-js';
import { DesignKitStore } from '../../store/DesignKitStore';
import type { SpringConfig } from '../../store/DesignKitStore';
import { Folder } from './Folder';
import { Slider } from './Slider';
import { SegmentedControl } from './SegmentedControl';
import { SpringVisualization } from './SpringVisualization';

interface SpringControlProps {
  panelId: string;
  path: string;
  label: string;
  spring: SpringConfig;
  onChange: (spring: SpringConfig) => void;
}

export function SpringControl(props: SpringControlProps) {
  const [mode, setMode] = createSignal<'simple' | 'advanced'>(
    DesignKitStore.getSpringMode(props.panelId, props.path)
  );

  // Subscribe to store changes for mode
  onMount(() => {
    const unsub = DesignKitStore.subscribe(props.panelId, () => {
      setMode(DesignKitStore.getSpringMode(props.panelId, props.path));
    });
    onCleanup(unsub);
  });

  const isSimpleMode = () => mode() === 'simple';

  const cache: {
    simple: SpringConfig;
    advanced: SpringConfig;
  } = {
    simple: props.spring.visualDuration !== undefined ? props.spring : { type: 'spring', visualDuration: 0.3, bounce: 0.2 },
    advanced: props.spring.stiffness !== undefined ? props.spring : { type: 'spring', stiffness: 200, damping: 25, mass: 1 },
  };

  const handleModeChange = (newMode: 'simple' | 'advanced') => {
    // Save current mode's values before switching
    if (isSimpleMode()) {
      cache.simple = props.spring;
    } else {
      cache.advanced = props.spring;
    }

    DesignKitStore.updateSpringMode(props.panelId, props.path, newMode);

    if (newMode === 'simple') {
      props.onChange(cache.simple);
    } else {
      props.onChange(cache.advanced);
    }
  };

  const handleUpdate = (key: keyof SpringConfig, value: number) => {
    if (isSimpleMode()) {
      const { stiffness, damping, mass, ...rest } = props.spring;
      props.onChange({ ...rest, [key]: value });
    } else {
      const { visualDuration, bounce, ...rest } = props.spring;
      props.onChange({ ...rest, [key]: value });
    }
  };

  return (
    <Folder title={props.label} defaultOpen={true}>
      <div style={{ display: 'flex', 'flex-direction': 'column', gap: '6px' }}>
        <SpringVisualization spring={props.spring} isSimpleMode={isSimpleMode()} />

        <div class="design-kit-labeled-control">
          <span class="design-kit-labeled-control-label">Type</span>
          <SegmentedControl
            options={[
              { value: 'simple' as const, label: 'Time' },
              { value: 'advanced' as const, label: 'Physics' },
            ]}
            value={mode()}
            onChange={handleModeChange}
          />
        </div>

        {isSimpleMode() ? (
          <>
            <Slider
              label="Duration"
              value={props.spring.visualDuration ?? 0.3}
              onChange={(v) => handleUpdate('visualDuration', v)}
              min={0.1}
              max={1}
              step={0.05}
              unit="s"
            />
            <Slider
              label="Bounce"
              value={props.spring.bounce ?? 0.2}
              onChange={(v) => handleUpdate('bounce', v)}
              min={0}
              max={1}
              step={0.05}
            />
          </>
        ) : (
          <>
            <Slider
              label="Stiffness"
              value={props.spring.stiffness ?? 400}
              onChange={(v) => handleUpdate('stiffness', v)}
              min={1}
              max={1000}
              step={10}
            />
            <Slider
              label="Damping"
              value={props.spring.damping ?? 17}
              onChange={(v) => handleUpdate('damping', v)}
              min={1}
              max={100}
              step={1}
            />
            <Slider
              label="Mass"
              value={props.spring.mass ?? 1}
              onChange={(v) => handleUpdate('mass', v)}
              min={0.1}
              max={10}
              step={0.1}
            />
          </>
        )}
      </div>
    </Folder>
  );
}

// src/svelte/components/SpringControl.svelte
<script lang="ts">
  import { DesignKitStore } from 'design-kit/store';
  import type { SpringConfig } from 'design-kit/store';
  import Folder from './Folder.svelte';
  import Slider from './Slider.svelte';
  import SegmentedControl from './SegmentedControl.svelte';
  import SpringVisualization from './SpringVisualization.svelte';

  let { panelId, path, label, spring, onChange } = $props<{
    panelId: string;
    path: string;
    label: string;
    spring: SpringConfig;
    onChange: (spring: SpringConfig) => void;
  }>();

  let mode = $state<'simple' | 'advanced'>(DesignKitStore.getSpringMode(panelId, path));

  $effect(() => {
    const unsub = DesignKitStore.subscribe(panelId, () => {
      mode = DesignKitStore.getSpringMode(panelId, path);
    });
    return unsub;
  });

  const isSimpleMode = $derived(mode === 'simple');

  const cache: {
    simple: SpringConfig;
    advanced: SpringConfig;
  } = {
    simple: spring.visualDuration !== undefined ? spring : { type: 'spring', visualDuration: 0.3, bounce: 0.2 },
    advanced: spring.stiffness !== undefined ? spring : { type: 'spring', stiffness: 200, damping: 25, mass: 1 },
  };

  const handleModeChange = (newMode: string) => {
    const typedMode = newMode as 'simple' | 'advanced';

    if (isSimpleMode) {
      cache.simple = spring;
    } else {
      cache.advanced = spring;
    }

    DesignKitStore.updateSpringMode(panelId, path, typedMode);

    if (typedMode === 'simple') {
      onChange(cache.simple);
    } else {
      onChange(cache.advanced);
    }
  };

  const handleUpdate = (key: keyof SpringConfig, value: number) => {
    if (isSimpleMode) {
      const { stiffness, damping, mass, ...rest } = spring;
      onChange({ ...rest, [key]: value });
    } else {
      const { visualDuration, bounce, ...rest } = spring;
      onChange({ ...rest, [key]: value });
    }
  };
</script>

<Folder title={label} defaultOpen={true}>
  <div style="display: flex; flex-direction: column; gap: 6px;">
    <SpringVisualization {spring} isSimpleMode={isSimpleMode} />

    <div class="design-kit-labeled-control">
      <span class="design-kit-labeled-control-label">Type</span>
      <SegmentedControl
        options={[
          { value: 'simple', label: 'Time' },
          { value: 'advanced', label: 'Physics' },
        ]}
        value={mode}
        onChange={handleModeChange}
      />
    </div>

    {#if isSimpleMode}
      <Slider
        label="Duration"
        value={spring.visualDuration ?? 0.3}
        onChange={(v) => handleUpdate('visualDuration', v)}
        min={0.1}
        max={1}
        step={0.05}
        unit="s"
      />
      <Slider
        label="Bounce"
        value={spring.bounce ?? 0.2}
        onChange={(v) => handleUpdate('bounce', v)}
        min={0}
        max={1}
        step={0.05}
      />
    {:else}
      <Slider
        label="Stiffness"
        value={spring.stiffness ?? 400}
        onChange={(v) => handleUpdate('stiffness', v)}
        min={1}
        max={1000}
        step={10}
      />
      <Slider
        label="Damping"
        value={spring.damping ?? 17}
        onChange={(v) => handleUpdate('damping', v)}
        min={1}
        max={100}
        step={1}
      />
      <Slider
        label="Mass"
        value={spring.mass ?? 1}
        onChange={(v) => handleUpdate('mass', v)}
        min={0.1}
        max={10}
        step={0.1}
      />
    {/if}
  </div>
</Folder>
