// src/solid/components/TextControl.tsx
import { createUniqueId } from 'solid-js';

interface TextControlProps {
  label: string;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
}

export function TextControl(props: TextControlProps) {
  const inputId = createUniqueId();

  return (
    <div class="design-kit-text-control">
      <label class="design-kit-text-label" for={inputId}>{props.label}</label>
      <input
        id={inputId}
        type="text"
        class="design-kit-text-input"
        value={props.value}
        onInput={(e) => props.onChange(e.currentTarget.value)}
        placeholder={props.placeholder}
      />
    </div>
  );
}

// src/svelte/components/TextControl.svelte
<script lang="ts">
  let { label, value, onChange, placeholder } = $props<{
    label: string;
    value: string;
    onChange: (value: string) => void;
    placeholder?: string;
  }>();
</script>

<div class="design-kit-text-control">
  <label class="design-kit-text-label">{label}</label>
  <input
    type="text"
    class="design-kit-text-input"
    value={value}
    placeholder={placeholder}
    oninput={(e) => onChange((e.currentTarget as HTMLInputElement).value)}
  />
</div>
